# Generated by Django 4.2.3 on 2023-09-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('folders', '0002_alter_folder_options_folder_created_folder_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='name',
        ),
        migrations.AddField(
            model_name='folder',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
