# Generated by Django 4.1.7 on 2023-06-03 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='북마크')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='북마크 설명')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크',
                'db_table': 'forum_bookmark',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='폴더')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='폴더 설명')),
            ],
            options={
                'verbose_name': '폴더',
                'verbose_name_plural': '폴더',
                'db_table': 'forum_folder',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updateDate', models.DateTimeField(auto_now_add=True, verbose_name='수정일')),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.bookmark', verbose_name='북마크')),
                ('folder', models.ManyToManyField(blank=True, to='forum.folder', verbose_name='폴더')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
                'db_table': 'forum_post',
            },
        ),
    ]
